const PRACTICE_TEMPLATE=[
  {id:'NLC',name:'ネオリンク',sector:'テクノロジー',price:1240,volatility:.018},
  {id:'MRT',name:'みらい電機',sector:'電力・インフラ',price:870,volatility:.012},
  {id:'SFO',name:'サンフーズ',sector:'食品',price:640,volatility:.015},
  {id:'BTA',name:'バンクタス',sector:'金融',price:1520,volatility:.016},
  {id:'KRT',name:'キラテック',sector:'製造業',price:980,volatility:.024}
];
let gameMode='practice',selectedDuration=180,stocks=[],selectedId='',secondsLeft=180,timerId=null,tick=0,cash=1000000,history=[],searchTerm='';
const yen=v=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Math.round(v));
const signedYen=v=>`${v>0?'+':v<0?'-':'±'}${yen(Math.abs(v))}`;
const pct=(v,b)=>b===0?0:v/b*100;
const formatTime=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const selectedStock=()=>stocks.find(s=>s.id===selectedId);
const totalStockValue=()=>stocks.reduce((sum,s)=>sum+s.price*s.holdings,0);
const totalAsset=()=>cash+totalStockValue();
const profit=()=>totalAsset()-1000000;
const el={
 startScreen:document.getElementById('startScreen'),loadingScreen:document.getElementById('loadingScreen'),gameScreen:document.getElementById('gameScreen'),resultScreen:document.getElementById('resultScreen'),startButton:document.getElementById('startButton'),restartButton:document.getElementById('restartButton'),modeDescription:document.getElementById('modeDescription'),loadingText:document.getElementById('loadingText'),loadingBar:document.getElementById('loadingBar'),gameModeLabel:document.getElementById('gameModeLabel'),hintText:document.getElementById('hintText'),chartTitle:document.getElementById('chartTitle'),stockSearch:document.getElementById('stockSearch'),stockList:document.getElementById('stockList'),selectedSector:document.getElementById('selectedSector'),selectedName:document.getElementById('selectedName'),selectedCode:document.getElementById('selectedCode'),selectedPrice:document.getElementById('selectedPrice'),selectedChange:document.getElementById('selectedChange'),chart:document.getElementById('chart'),timer:document.getElementById('timer'),marketTick:document.getElementById('marketTick'),quantityInput:document.getElementById('quantityInput'),buyButton:document.getElementById('buyButton'),sellButton:document.getElementById('sellButton'),orderMessage:document.getElementById('orderMessage'),holdingLabel:document.getElementById('holdingLabel'),cash:document.getElementById('cash'),holdingCount:document.getElementById('holdingCount'),stockValue:document.getElementById('stockValue'),totalAsset:document.getElementById('totalAsset'),profit:document.getElementById('profit'),profitRate:document.getElementById('profitRate'),profitCard:document.getElementById('profitCard'),history:document.getElementById('history'),resultAsset:document.getElementById('resultAsset'),resultProfit:document.getElementById('resultProfit'),resultStats:document.getElementById('resultStats')
};
function makePracticeStocks(){return PRACTICE_TEMPLATE.map(s=>({...s,code:s.id,open:s.price,history:Array.from({length:40},()=>s.price),holdings:0,replay:null}))}
function setMode(mode,duration=180){gameMode=mode;selectedDuration=duration;document.querySelectorAll('.game-choice').forEach(card=>card.classList.toggle('selected',card.dataset.mode===mode));document.querySelectorAll('.duration-button').forEach(btn=>btn.classList.toggle('selected',btn.dataset.mode===mode&&Number(btn.dataset.duration)===duration));if(mode==='practice'){el.modeDescription.innerHTML='<div class="rule-label">練習用のルール</div><ul><li>初期資金は100万円。5つの架空企業から自由に売買します。</li><li>株価は毎秒ランダムに変わります。手数料・借金・空売りはありません。</li><li>終了時の総資産で結果を確認します。</li></ul>';el.startButton.innerHTML='練習用を始める <span>→</span>'}else{el.modeDescription.innerHTML='<div class="rule-label">本番用のルール</div><ul><li>実在企業130社以上を表示します。価格の土台は2024年8月5日の実際の日足データです。</li><li>開始価格・終値・高値・安値をもとに、授業用の1秒チャートへ再構成します。</li><li>短期の売買で、結果が大きく変わることを体験します。</li></ul>';el.startButton.innerHTML='本番用を始める <span>→</span>'}}
function resetGame(){stocks.forEach(s=>{s.price=s.open;s.history=Array.from({length:40},()=>s.open);s.holdings=0});selectedId=stocks[0]?.id||'';secondsLeft=selectedDuration;tick=0;cash=1000000;history=[];searchTerm='';el.stockSearch.value=''}
function filteredStocks(){const q=searchTerm.trim().toLowerCase();return q?stocks.filter(s=>`${s.name} ${s.code} ${s.sector}`.toLowerCase().includes(q)):stocks}
function renderStocks(){const visible=filteredStocks();el.stockList.innerHTML=visible.map(s=>{const d=s.price-s.open,up=d>=0;return `<button type="button" class="stock-row ${s.id===selectedId?'active':''}" data-stock="${s.id}"><span><span class="stock-name">${s.name}</span><span class="stock-sector">${s.code} / ${s.sector}</span></span><span><span class="stock-price">${yen(s.price)}</span><span class="stock-move ${up?'price-up':'price-down'}">${up?'+':''}${pct(d,s.open).toFixed(2)}%</span></span></button>`}).join('')||'<p class="empty-history">該当する銘柄がありません。</p>';el.stockList.querySelectorAll('[data-stock]').forEach(btn=>btn.addEventListener('click',()=>{selectedId=btn.dataset.stock;render()}))}
function renderChart(stock){if(!stock)return;const data=stock.history,w=900,h=300,p={l:18,r:18,t:18,b:30},min=Math.min(...data),max=Math.max(...data),spread=Math.max(1,max-min),low=min-spread*.2,high=max+spread*.2,x=i=>p.l+i*(w-p.l-p.r)/(data.length-1),y=v=>p.t+(high-v)*(h-p.t-p.b)/(high-low),line=data.map((v,i)=>`${i?'L':'M'} ${x(i).toFixed(1)} ${y(v).toFixed(1)}`).join(' '),area=`${line} L ${x(data.length-1).toFixed(1)} ${h-p.b} L ${x(0).toFixed(1)} ${h-p.b} Z`,up=data.at(-1)>=data[0],color=up?'#c9403d':'#2f74bb',grid=[.2,.5,.8].map(k=>{const gy=p.t+(h-p.t-p.b)*k;return `<line x1="${p.l}" y1="${gy}" x2="${w-p.r}" y2="${gy}" stroke="#e4e9f0" stroke-dasharray="4 5"/>`}).join('');el.chart.innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-color="${color}" stop-opacity=".18"/><stop offset="100%" stop-color="${color}" stop-opacity="0"/></linearGradient></defs>${grid}<path d="${area}" fill="url(#fill)"/><path d="${line}" fill="none" stroke="${color}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><circle cx="${x(data.length-1)}" cy="${y(data.at(-1))}" r="6" fill="${color}" stroke="#fff" stroke-width="3"/><text x="${p.l}" y="${h-7}" fill="#8994a5" font-size="12">40秒前</text><text x="${w-p.r-34}" y="${h-7}" fill="#8994a5" font-size="12">現在</text></svg>`}
function renderQuote(){const s=selectedStock();if(!s)return;const d=s.price-s.open,r=pct(d,s.open),up=d>=0;el.selectedSector.textContent=s.sector;el.selectedName.textContent=s.name;el.selectedCode.textContent=s.code;el.selectedPrice.textContent=yen(s.price);el.selectedChange.textContent=`${d>=0?'+':''}${yen(d)} (${r>=0?'+':''}${r.toFixed(2)}%)`;el.selectedChange.className=up?'price-up':'price-down';el.holdingLabel.textContent=`保有 ${s.holdings}株`;renderChart(s)}
function renderPortfolio(){const sv=totalStockValue(),ta=totalAsset(),p=profit(),r=pct(p,1000000),cnt=stocks.filter(s=>s.holdings>0).length;el.cash.textContent=yen(cash);el.holdingCount.textContent=`${cnt}銘柄`;el.stockValue.textContent=yen(sv);el.totalAsset.textContent=yen(ta);el.profit.textContent=signedYen(p);el.profitRate.textContent=`${r>=0?'+':''}${r.toFixed(2)}%`;el.profitCard.className=`profit-card ${p>0?'positive':p<0?'negative':'neutral'}`}
function renderHistory(){if(!history.length){el.history.innerHTML='<p class="empty-history">まだ取引はありません。</p>';return}el.history.innerHTML=history.slice(0,16).map(t=>`<div class="history-item ${t.type}"><div class="history-main"><span>${t.type==='buy'?'購入':'売却'} ${t.name}</span><span>${yen(t.amount)}</span></div><div class="history-sub">${t.qty}株 × ${yen(t.price)} / TICK ${t.tick}</div></div>`).join('')}
function render(){el.timer.textContent=formatTime(secondsLeft);el.marketTick.textContent=`TICK ${tick}`;renderStocks();renderQuote();renderPortfolio();renderHistory()}
function updateMarket(){tick++;stocks.forEach(s=>{if(gameMode==='main'&&s.replay){s.price=s.replay[Math.min(tick,s.replay.length-1)]}else{const shock=(Math.random()-.5)*2*s.volatility,micro=(Math.random()-.5)*.004;s.price=Math.round(Math.max(40,s.price*(1+shock+micro)))}s.history.push(s.price);if(s.history.length>40)s.history.shift()});secondsLeft--;render();if(secondsLeft<=0)endGame()}
function message(t,type){el.orderMessage.textContent=t;el.orderMessage.style.color=type==='error'?'#bc3430':'#287b57'}
function addTrade(type){const s=selectedStock(),q=Math.max(1,Math.floor(Number(el.quantityInput.value)||0)),a=s.price*q;if(type==='buy'){if(a>cash){message('現金残高が足りません。株数を減らしてください。','error');return}cash-=a;s.holdings+=q;history.unshift({type,name:s.name,qty:q,price:s.price,amount:a,tick});message(`${s.name}を${q}株購入しました。`,'ok')}else{if(q>s.holdings){message(`売却できるのは${s.holdings}株までです。`,'error');return}cash+=a;s.holdings-=q;history.unshift({type,name:s.name,qty:q,price:s.price,amount:a,tick});message(`${s.name}を${q}株売却しました。`,'ok')}render()}
function beginGame(){resetGame();el.startScreen.classList.add('hidden');el.loadingScreen.classList.add('hidden');el.resultScreen.classList.add('hidden');el.gameScreen.classList.remove('hidden');el.gameModeLabel.textContent=gameMode==='main'?'本番用 / 実在企業・2024年8月5日再現':'練習用 / 架空企業5社';el.chartTitle.textContent=gameMode==='main'?'授業用1秒リプレイ（実際の日足を基準）':'1秒足チャート';el.hintText.innerHTML=gameMode==='main'?'2024年8月5日の始値・高値・安値・終値をもとにした授業用再現です。<br><strong>途中の1秒ごとの動きは、予測できません。</strong>':'表示されるのは短期の価格変動だけです。<br><strong>次の1秒を当てる材料はありません。</strong>';render();timerId=setInterval(updateMarket,1000)}
function endGame(){clearInterval(timerId);el.gameScreen.classList.add('hidden');el.resultScreen.classList.remove('hidden');const a=totalAsset(),p=profit(),r=pct(p,1000000),tr=history.length,held=stocks.filter(s=>s.holdings>0).length;el.resultAsset.textContent=yen(a);el.resultProfit.textContent=`${signedYen(p)}（${r>=0?'+':''}${r.toFixed(2)}%）`;el.resultProfit.className=`result-profit ${p>0?'positive':p<0?'negative':'neutral'}`;el.resultStats.innerHTML=`<div><span>売買回数</span><strong>${tr}回</strong></div><div><span>保有銘柄数</span><strong>${held}銘柄</strong></div><div><span>プレイ時間</span><strong>${Math.floor(selectedDuration/60)}分</strong></div>`}
function interpolate(points,length){const arr=[];for(let i=0;i<=length;i++){const t=i/length;let a=points[0],b=points.at(-1);for(let j=0;j<points.length-1;j++){if(t>=points[j].t&&t<=points[j+1].t){a=points[j];b=points[j+1];break}}const raw=a.v+(b.v-a.v)*((t-a.t)/(b.t-a.t));const wiggle=Math.sin(i*1.77)*Math.max(1,raw*.004)*(Math.sin(i*.29)*.5+.5);arr.push(Math.max(1,Math.round(raw+wiggle)))}arr[0]=Math.round(points[0].v);arr[arr.length-1]=Math.round(points.at(-1).v);return arr}
function toTokyoDate(ts){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(ts*1000))}
async function getDaily(company){const from=Date.UTC(2024,7,1)/1000,to=Date.UTC(2024,7,7)/1000;const url=`https://query1.finance.yahoo.com/v8/finance/chart/${company.ticker}?period1=${from}&period2=${to}&interval=1d&events=history`;const res=await fetch(url);if(!res.ok)throw new Error('data unavailable');const json=await res.json();const r=json.chart?.result?.[0];if(!r)throw new Error('no result');const q=r.indicators.quote[0];const rows=r.timestamp.map((ts,i)=>({date:toTokyoDate(ts),open:q.open[i],high:q.high[i],low:q.low[i],close:q.close[i]})).filter(x=>x.close&&x.open&&x.high&&x.low);const prev=rows.find(x=>x.date==='2024-08-02'),day=rows.find(x=>x.date==='2024-08-05');if(!prev||!day)throw new Error('missing date');return {prev,day}}
async function loadMainStocks(){el.startScreen.classList.add('hidden');el.loadingScreen.classList.remove('hidden');el.loadingBar.style.width='4%';const companies=window.REAL_COMPANIES||[];const result=[];let done=0;const worker=async()=>{while(companies.length){const c=companies.shift();try{const {prev,day}=await getDaily(c);const lowFirst=(Number(c.code)%2===0);const midA=lowFirst?day.low:day.high,midB=lowFirst?day.high:day.low;const replay=interpolate([{t:0,v:prev.close},{t:.09,v:day.open},{t:.38,v:midA},{t:.68,v:midB},{t:1,v:day.close}],selectedDuration);result.push({id:c.code,code:c.code,name:c.name,sector:c.sector,price:Math.round(prev.close),open:Math.round(prev.close),history:Array.from({length:40},()=>Math.round(prev.close)),holdings:0,replay});}catch(e){}done++;if(done%5===0){el.loadingText.textContent=`実在企業の過去価格を読み込み中… ${result.length}社準備済み`;el.loadingBar.style.width=`${Math.min(94,4+done/(window.REAL_COMPANIES.length||1)*90)}%`}}};await Promise.all(Array.from({length:10},worker));if(result.length<100){el.loadingText.textContent='価格データを100社分取得できませんでした。通信環境を確認して、もう一度お試しください。';el.loadingBar.style.width='100%';setTimeout(()=>{el.loadingScreen.classList.add('hidden');el.startScreen.classList.remove('hidden')},2200);return}stocks=result.sort((a,b)=>a.code.localeCompare(b.code));el.loadingBar.style.width='100%';beginGame()}
async function startSelectedGame(){clearInterval(timerId);if(gameMode==='practice'){stocks=makePracticeStocks();beginGame()}else{await loadMainStocks()}}
document.querySelectorAll('.game-choice').forEach(card=>card.addEventListener('click',e=>{if(e.target.closest('.duration-button'))return;setMode(card.dataset.mode,gameMode===card.dataset.mode?selectedDuration:180)}));document.querySelectorAll('.duration-button').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();setMode(btn.dataset.mode,Number(btn.dataset.duration))}));el.startButton.addEventListener('click',startSelectedGame);el.restartButton.addEventListener('click',()=>{el.resultScreen.classList.add('hidden');el.startScreen.classList.remove('hidden')});el.buyButton.addEventListener('click',()=>addTrade('buy'));el.sellButton.addEventListener('click',()=>addTrade('sell'));document.querySelectorAll('[data-qty]').forEach(b=>b.addEventListener('click',()=>el.quantityInput.value=b.dataset.qty));el.stockSearch.addEventListener('input',e=>{searchTerm=e.target.value;renderStocks()});setMode('practice',180);stocks=makePracticeStocks();render();