const stocks=[{id:'NLC',name:'ネオリンク',sector:'テクノロジー',price:1240,volatility:.018},{id:'MRT',name:'みらい電機',sector:'電力・インフラ',price:870,volatility:.012},{id:'SFO',name:'サンフーズ',sector:'食品',price:640,volatility:.015},{id:'BTA',name:'バンクタス',sector:'金融',price:1520,volatility:.016},{id:'KRT',name:'キラテック',sector:'製造業',price:980,volatility:.024}].map(s=>({...s,open:s.price,history:Array.from({length:40},()=>s.price),holdings:0}));
let selectedDuration=180,selectedId='NLC',secondsLeft=180,timerId=null,tick=0,cash=1000000,history=[];
const yen=v=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Math.round(v));
const signedYen=v=>`${v>0?'+':v<0?'-':'±'}${yen(Math.abs(v))}`;
const selectedStock=()=>stocks.find(s=>s.id===selectedId);
const totalStockValue=()=>stocks.reduce((sum,s)=>sum+s.price*s.holdings,0);
const totalAsset=()=>cash+totalStockValue();
const profit=()=>totalAsset()-1000000;
const pct=(v,b)=>b===0?0:v/b*100;
const formatTime=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const el={startScreen:document.getElementById('startScreen'),gameScreen:document.getElementById('gameScreen'),resultScreen:document.getElementById('resultScreen'),startButton:document.getElementById('startButton'),restartButton:document.getElementById('restartButton'),stockList:document.getElementById('stockList'),selectedSector:document.getElementById('selectedSector'),selectedName:document.getElementById('selectedName'),selectedCode:document.getElementById('selectedCode'),selectedPrice:document.getElementById('selectedPrice'),selectedChange:document.getElementById('selectedChange'),chart:document.getElementById('chart'),timer:document.getElementById('timer'),marketTick:document.getElementById('marketTick'),quantityInput:document.getElementById('quantityInput'),buyButton:document.getElementById('buyButton'),sellButton:document.getElementById('sellButton'),orderMessage:document.getElementById('orderMessage'),holdingLabel:document.getElementById('holdingLabel'),cash:document.getElementById('cash'),holdingCount:document.getElementById('holdingCount'),stockValue:document.getElementById('stockValue'),totalAsset:document.getElementById('totalAsset'),profit:document.getElementById('profit'),profitRate:document.getElementById('profitRate'),profitCard:document.getElementById('profitCard'),history:document.getElementById('history'),resultAsset:document.getElementById('resultAsset'),resultProfit:document.getElementById('resultProfit'),resultStats:document.getElementById('resultStats')};
function resetGame(){stocks.forEach(s=>{s.price=s.open;s.history=Array.from({length:40},()=>s.open);s.holdings=0});selectedId='NLC';secondsLeft=selectedDuration;tick=0;cash=1000000;history=[]}
function renderStocks(){el.stockList.innerHTML=stocks.map(s=>{const d=s.price-s.open,up=d>=0;return `<button type="button" class="stock-row ${s.id===selectedId?'active':''}" data-stock="${s.id}"><span><span class="stock-name">${s.name}</span><span class="stock-sector">${s.id} / ${s.sector}</span></span><span><span class="stock-price">${yen(s.price)}</span><span class="stock-move ${up?'price-up':'price-down'}">${up?'+':''}${pct(d,s.open).toFixed(2)}%</span></span></button>`}).join('');el.stockList.querySelectorAll('[data-stock]').forEach(btn=>btn.addEventListener('click',()=>{selectedId=btn.dataset.stock;render()}))}
function renderChart(stock){const data=stock.history,w=900,h=300,p={l:18,r:18,t:18,b:30},min=Math.min(...data),max=Math.max(...data),spread=Math.max(1,max-min),low=min-spread*.2,high=max+spread*.2,x=i=>p.l+i*(w-p.l-p.r)/(data.length-1),y=v=>p.t+(high-v)*(h-p.t-p.b)/(high-low),line=data.map((v,i)=>`${i?'L':'M'} ${x(i).toFixed(1)} ${y(v).toFixed(1)}`).join(' '),area=`${line} L ${x(data.length-1).toFixed(1)} ${h-p.b} L ${x(0).toFixed(1)} ${h-p.b} Z`,up=data.at(-1)>=data[0],color=up?'#c9403d':'#2f74bb',grid=[.2,.5,.8].map(k=>{const gy=p.t+(h-p.t-p.b)*k;return `<line x1="${p.l}" y1="${gy}" x2="${w-p.r}" y2="${gy}" stroke="#e4e9f0" stroke-dasharray="4 5"/>`}).join('');el.chart.innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-color="${color}" stop-opacity=".18"/><stop offset="100%" stop-color="${color}" stop-opacity="0"/></linearGradient></defs>${grid}<path d="${area}" fill="url(#fill)"/><path d="${line}" fill="none" stroke="${color}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><circle cx="${x(data.length-1)}" cy="${y(data.at(-1))}" r="6" fill="${color}" stroke="#fff" stroke-width="3"/><text x="${p.l}" y="${h-7}" fill="#8994a5" font-size="12">40秒前</text><text x="${w-p.r-34}" y="${h-7}" fill="#8994a5" font-size="12">現在</text></svg>`}
function renderQuote(){const s=selectedStock(),d=s.price-s.open,r=pct(d,s.open),up=d>=0;el.selectedSector.textContent=s.sector;el.selectedName.textContent=s.name;el.selectedCode.textContent=s.id;el.selectedPrice.textContent=yen(s.price);el.selectedChange.textContent=`${d>=0?'+':''}${yen(d)} (${r>=0?'+':''}${r.toFixed(2)}%)`;el.selectedChange.className=up?'price-up':'price-down';el.holdingLabel.textContent=`保有 ${s.holdings}株`;renderChart(s)}
function renderPortfolio(){const sv=totalStockValue(),ta=totalAsset(),p=profit(),r=pct(p,1000000),cnt=stocks.filter(s=>s.holdings>0).length;el.cash.textContent=yen(cash);el.holdingCount.textContent=`${cnt}銘柄`;el.stockValue.textContent=yen(sv);el.totalAsset.textContent=yen(ta);el.profit.textContent=signedYen(p);el.profitRate.textContent=`${r>=0?'+':''}${r.toFixed(2)}%`;el.profitCard.className=`profit-card ${p>0?'positive':p<0?'negative':'neutral'}`}
function renderHistory(){if(!history.length){el.history.innerHTML='<p class="empty-history">まだ取引はありません。</p>';return}el.history.innerHTML=history.slice(0,16).map(t=>`<div class="history-item ${t.type}"><div class="history-main"><span>${t.type==='buy'?'購入':'売却'} ${t.name}</span><span>${yen(t.amount)}</span></div><div class="history-sub">${t.qty}株 × ${yen(t.price)} / TICK ${t.tick}</div></div>`).join('')}
function render(){el.timer.textContent=formatTime(secondsLeft);el.marketTick.textContent=`TICK ${tick}`;renderStocks();renderQuote();renderPortfolio();renderHistory()}
function updateMarket(){tick++;stocks.forEach(s=>{const shock=(Math.random()-.5)*2*s.volatility,micro=(Math.random()-.5)*.004;s.price=Math.round(Math.max(40,s.price*(1+shock+micro)));s.history.push(s.price);if(s.history.length>40)s.history.shift()});secondsLeft--;render();if(secondsLeft<=0)endGame()}
function message(t,type){el.orderMessage.textContent=t;el.orderMessage.style.color=type==='error'?'#bc3430':'#287b57'}
function addTrade(type){const s=selectedStock(),q=Math.max(1,Math.floor(Number(el.quantityInput.value)||0)),a=s.price*q;if(type==='buy'){if(a>cash){message('現金残高が足りません。株数を減らしてください。','error');return}cash-=a;s.holdings+=q;history.unshift({type,name:s.name,qty:q,price:s.price,amount:a,tick});message(`${s.name}を${q}株購入しました。`,'ok')}else{if(q>s.holdings){message(`売却できるのは${s.holdings}株までです。`,'error');return}cash+=a;s.holdings-=q;history.unshift({type,name:s.name,qty:q,price:s.price,amount:a,tick});message(`${s.name}を${q}株売却しました。`,'ok')}render()}
function startGame(){resetGame();el.startScreen.classList.add('hidden');el.resultScreen.classList.add('hidden');el.gameScreen.classList.remove('hidden');render();timerId=setInterval(updateMarket,1000)}
function endGame(){clearInterval(timerId);el.gameScreen.classList.add('hidden');el.resultScreen.classList.remove('hidden');const a=totalAsset(),p=profit(),r=pct(p,1000000),tr=history.length,held=stocks.filter(s=>s.holdings>0).length;el.resultAsset.textContent=yen(a);el.resultProfit.textContent=`${signedYen(p)}（${r>=0?'+':''}${r.toFixed(2)}%）`;el.resultProfit.className=`result-profit ${p>0?'positive':p<0?'negative':'neutral'}`;el.resultStats.innerHTML=`<div><span>売買回数</span><strong>${tr}回</strong></div><div><span>保有銘柄数</span><strong>${held}銘柄</strong></div><div><span>プレイ時間</span><strong>${Math.floor(selectedDuration/60)}分</strong></div>`}
document.querySelectorAll('.mode-card').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.mode-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedDuration=Number(b.dataset.duration)}));el.startButton.addEventListener('click',startGame);el.restartButton.addEventListener('click',()=>{el.resultScreen.classList.add('hidden');el.startScreen.classList.remove('hidden')});el.buyButton.addEventListener('click',()=>addTrade('buy'));el.sellButton.addEventListener('click',()=>addTrade('sell'));document.querySelectorAll('[data-qty]').forEach(b=>b.addEventListener('click',()=>el.quantityInput.value=b.dataset.qty));render();